import assert from 'node:assert/strict';
import test from 'node:test';
import { parseAptDatAirport } from './extractor/xplane-apt.js';
import { buildReferenceScene } from '../contribution-editor/reference-scene.js';

const APT_FIXTURE = `I
1200 Generated by WorldEditor

1 1887 0 0 YSCB Canberra
1302 icao_code YSCB
100 45.00 1 0 0.25 1 2 0 17 -35.2906490 149.1944500 0 0 3 0 0 0 35 -35.3174753 149.1944496 300 329 3 4 1 0
120 Taxiway centreline
111 -35.3000000 149.1900000 1 101
112 -35.3001000 149.1902000 -35.3000500 149.1901000 1 101
115 -35.3002000 149.1904000
120 Runway hold
111 -35.3010000 149.1910000 4 103
115 -35.3010000 149.1912000
120 Taxi edge
111 -35.3020000 149.1920000 0 102
115 -35.3020000 149.1922000

1 10 0 0 YSSY Sydney
100 45.00 1 0 0.25 1 2 0 16L -33.9500000 151.1700000 0 0 3 0 0 0 34R -33.9300000 151.1800000 0 0 3 0 0 0
`;

test('extracts only the requested airport and maps X-Plane light codes', () => {
  const result = parseAptDatAirport(APT_FIXTURE, {
    icao: 'YSCB',
    sourceFile: 'Global Airports/Earth nav data/apt.dat',
  });

  assert.equal(result.airportIdentifier, 'YSCB');
  assert.equal(result.airportName, 'Canberra');
  assert.equal(result.runways.length, 1);
  assert.equal(result.runways[0].sourceType, 'xplane-runway');
  assert.equal(result.runways[0].materialKind, 'asphalt-medium');
  assert.equal(result.runways[0].first.markingCode, 3);
  assert.ok(result.runways[0].lengthMeters > 1000);
  assert.ok(result.runwayLightZones.length > 0);
  assert.deepEqual(
    result.runwayLightZones
      .filter(
        (zone) =>
          zone.lightType.includes('runway-edge-') && zone.lightType.endsWith('-continuous-envelope')
      )
      .map((zone) => zone.geometryType),
    ['LineString', 'LineString']
  );
  assert.deepEqual(
    result.lightRows
      .filter((row) => row.sourceType === 'xplane-apt-light-string')
      .map((row) => [row.lightCode, row.classification]),
    [
      [101, 'taxi-centerline'],
      [103, 'stopbar'],
      [102, 'taxi-edge'],
    ]
  );
  assert.ok(result.lightRows[0].vertices.length > 3, 'Bezier light strings are sampled');
  assert.equal(result.lightRows[0].sourceType, 'xplane-apt-light-string');
  assert.match(result.lightRows[0].sourceFeatureId, /^[a-f0-9]{16}$/);
  assert.equal(result.lightRows[0].sourceRunIndex, 0);
  const markings = result.lightRows.filter(
    (row) => row.sourceType === 'xplane-apt-painted-marking'
  );
  assert.deepEqual(
    markings.map((row) => [row.markingCode, row.classification]),
    [
      [1, 'taxi-centerline'],
      [4, 'stopbar'],
    ]
  );
  assert.ok(markings.every((row) => row.placementOnly && row.removalEligible === false));

  const scene = buildReferenceScene(result, 'xplane');
  assert.ok(
    scene.features.some(
      (feature) =>
        feature.properties.sourceType === 'xplane-apt-runway-generated' &&
        feature.properties.semanticType === 'runway-marking'
    )
  );
  const runwayCentreline = scene.features.find(
    (feature) =>
      feature.properties.sourceType === 'xplane-apt-runway-generated' &&
      feature.geometry.type === 'LineString' &&
      feature.properties.semanticType === 'runway-marking'
  );
  assert.equal(runwayCentreline.properties.markingColor, '#f5f5f4');
  assert.equal(runwayCentreline.properties.renderPattern, 'apt-marking-22');
  assert.ok(
    scene.features.some(
      (feature) =>
        feature.geometry.type === 'Polygon' && feature.properties.title === 'Runway designation 17'
    )
  );
  assert.ok(scene.features.some((feature) => feature.properties.lightColor));
});

test('returns null when the selected airport is not present', () => {
  assert.equal(parseAptDatAirport(APT_FIXTURE, { icao: 'YMML' }), null);
});

test('recognizes an ICAO supplied by airport metadata', () => {
  const result = parseAptDatAirport(
    `I
1200 Test
1 10 0 0 X123 Gateway airport
1302 icao_code YPAD
120 Centreline
111 -34.9400 138.5300 1 101
115 -34.9401 138.5301
`,
    { icao: 'YPAD' }
  );
  assert.equal(result.airportIdentifier, 'YPAD');
  assert.equal(
    result.lightRows.filter((row) => row.sourceType === 'xplane-apt-light-string').length,
    1
  );
});

test('retains the complete apt.dat paint palette and black-border variants', () => {
  const result = parseAptDatAirport(
    `I
1200 Test
1 10 0 0 TEST Road markings
120 Road edge
111 -31.0000 115.0000 20
115 -31.0001 115.0001
120 Bordered road edge
111 -31.0002 115.0002 70
115 -31.0003 115.0003
`,
    { icao: 'TEST' }
  );

  assert.deepEqual(
    result.lightRows
      .filter((row) => row.sourceType === 'xplane-apt-painted-marking')
      .map((row) => [row.markingCode, row.markingDescription]),
    [
      [20, 'solid white roadway edge'],
      [70, 'solid white roadway edge'],
    ]
  );
});

test('extracts helipads, taxi routes, signs, and ramp starts as optional map signals', () => {
  const result = parseAptDatAirport(
    `I
1200 Test
1 10 0 0 TEST Detailed airport
102 H1 -31.0000 115.0000 90 20 18 53 0 0 0.25 1
20 -31.0001 115.0001 180 0 2 {@L}A
1200
1201 -31.0000 115.0000 both 10 A_start
1201 -31.0002 115.0002 both 11 A_end
1202 10 11 twoway taxiway_c A
1300 -31.0003 115.0003 90 gate jets A1
`,
    { icao: 'TEST' }
  );
  const types = result.referenceFeatures.map((feature) => feature.properties.semanticType);

  assert.ok(types.includes('helipad'));
  assert.ok(types.includes('taxiway-sign'));
  assert.ok(types.includes('atc-taxi-route'));
  assert.ok(types.includes('ramp-start'));
  assert.equal(
    result.referenceFeatures.find((feature) => feature.properties.semanticType === 'helipad')
      .properties.materialKind,
    'concrete-medium'
  );
});

test('collapses WED split Bezier records instead of drawing zero-length connector loops', () => {
  const result = parseAptDatAirport(
    `I
1200 Test
1 10 0 0 TEST Split bezier
120 Curved centreline
111 -31.0000 115.0000 1 101
112 -31.0001 115.0001 -31.00005 115.00005 1 101
111 -31.0001 115.0001 1 101
112 -31.0001 115.0001 -31.00015 115.00015 1 101
115 -31.0002 115.0002
`,
    { icao: 'TEST' }
  );

  const vertices = result.lightRows.find(
    (row) => row.sourceType === 'xplane-apt-light-string'
  ).vertices;
  assert.ok(vertices.length > 4);
  assert.equal(
    vertices.filter(
      (vertex, index) =>
        index > 0 &&
        vertex.lat === vertices[index - 1].lat &&
        vertex.lon === vertices[index - 1].lon
    ).length,
    0
  );
  assert.ok(vertices.every((vertex) => vertex.lat <= -31 && vertex.lat >= -31.0002));
  assert.ok(vertices.every((vertex) => vertex.lon >= 115 && vertex.lon <= 115.0002));
});

test('protects explicit X-Plane lighting objects as non-target fixtures', () => {
  const result = parseAptDatAirport(
    `I
1200 Test
1 10 0 0 TEST Lighting fixtures
21 -31.0001 115.0001 2 180.0 3.0
21 -31.0002 115.0002 6 180.0 0.0
120 Centreline
111 -31.0000 115.0000 1 101
115 -31.0001 115.0001
`,
    { icao: 'TEST' }
  );

  assert.deepEqual(
    result.instances.map((instance) => instance.classification),
    ['runway', 'runway-guard']
  );
});

test('keeps apt.dat pavement holes in the same polygon and rejects open contours', () => {
  const result = parseAptDatAirport(
    `I
1200 Test
1 10 0 0 TEST Pavement rings
110 1 0.25 0 Apron with island
111 -31.0000 115.0000
111 -31.0000 115.0010
111 -31.0010 115.0010
113 -31.0010 115.0000
111 -31.0003 115.0003
111 -31.0007 115.0003
111 -31.0007 115.0007
113 -31.0003 115.0007
110 2 0.25 0 Broken pavement
111 -31.0020 115.0000
111 -31.0020 115.0010
115 -31.0030 115.0010
`,
    { icao: 'TEST', sourceFile: 'Earth nav data/apt.dat' }
  );

  assert.equal(result.referenceFeatures.length, 1);
  assert.equal(result.referenceFeatures[0].geometry.type, 'Polygon');
  assert.equal(result.referenceFeatures[0].geometry.coordinates.length, 2);
  assert.ok(result.referenceFeatures[0].geometry.coordinates.every((ring) => ring.length === 5));
  assert.match(result.warnings[0], /ignored open apt\.dat pavement contour/);
});
